# fly.toml app configuration file generated for assistent-voice on 2025-07-09T23:23:07+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'assistent-voice'
primary_region = 'cdg'

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 1


# Comando para iniciar o servidor Uvicorn corretamente no Fly.io
[experimental]
  cmd = ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]

[deploy]
  release_command = "echo 'Deploying assistent-voice'"
